############### 数据库配置 ###############
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.86.184:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

############### 日志配置 ###############
logging:
  level:
    root: warn
    com.ccy.mybatisdemo.dao: trace
  pattern:
    console: '%p%m%n'
