############### 数据库配置 ###############
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.108:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

############### 日志配置 ###############
logging:
  level:
    root: warn
    com.ccy.mybatisdemo.dao: trace
  pattern:
    console: '%p%m%n'

############### mybatis-plus配置 ###############
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #xml中resultType值的前缀设置 不用写全路径了
  type-aliases-package: com.ccy.mybatisdemo.entity
#  global-config:
#    db-config:
#      #数据表前缀
#      table-prefix: prs_
#      id-type: uuid  #全局设置主键id的类型
    #进阶配置
  #  configuration:
  #    map-underscore-to-camel-case: true